### ISSUE TITLE
how about this API SoftModalMessageBox

### ISSUE THREAD

**Issue by loquat** [cristianbuse/VBA-MessageBox#1]
Private Declare Function SoftModalMessageBox Lib "user32" (pMsgBoxParams As Any) As Long

Public Enum eMsgParams
    cbSize
    hWndOwner
    hInstance
    lpszText
    lpszCaption
    dwStyle
    lpszIcon
    dwContextHelpId
    lpfnMsgBoxCallback 'call back
    dwLanguageId
    pwndOwner
    wLanguageId
    pidButton
    ppszButtonText
    cButtons
    DefButton
    CancelID
    Timeout
    unk2_2 = 21
    unk2_3
    unk2_4
End Enum

Public Enum WindowsVersion
    Earlier
    Later
End Enum

Public WinVersion As WindowsVersion

Public Function WindowsVersion() As Long
    ' Windows 10 100
    ' Windows 8.1 63
    ' Windows 8.0 62
    ' Windows 7 61
    ' Windows Vista 60
    ' Windows XP 51
    ' Windows 2000 50
    Dim SystemSet As Object
    Dim System As Object
    Dim S As String
    Dim i As Long
    Set SystemSet = GetObject("winmgmts:").InstancesOf("Win32_OperatingSystem")
    For Each System In SystemSet
    S = System.Version
    Next
    i = InStr(S, ".")
    S = Left$(S, i - 1) & Mid$(S, i + 1)
    i = InStr(S, ".")
    If i Then S = Left$(S, i - 1)
    WindowsVersion = Val(S)
End Function

Public Function MsgBoxEx(arrText$, strTitle$, strPrompt$, Optional ByVal DefButton As Long = 0, Optional ByVal Timeout As Long = -1, Optional ByVal CancelID As Boolean = True)
    Dim md_msg() As Long
    Dim lBtn() As Long
    Dim sTxt() As String
    Dim i&, U&
    If WindowsVersion() < 61 Then
        WinVersion = Earlier
        ReDim md_msg(17) As Long
    Else
        WinVersion = Later
        ReDim md_msg(24) As Long
    End If
    mySplit arrText, sTxt, "|" 'better than vba.split
    U = UBound(sTxt)
    ReDim lBtn(U) As Long
    For i = 0 To U '
    lBtn(i) = U - i + 2 '5 4 3 2, and 2 is the last
    Next i
    md_msg(eMsgParams.cbSize) = 40 '
    md_msg(eMsgParams.lpszText) = StrPtr(strPrompt)
    md_msg(eMsgParams.lpszCaption) = StrPtr(strTitle)
    md_msg(eMsgParams.dwStyle) = vbYesNo 'odd, should set this
    md_msg(eMsgParams.DefButton + WinVersion) = DefButton - 1 
    md_msg(eMsgParams.CancelID + WinVersion) = CancelID '
    md_msg(eMsgParams.cButtons + WinVersion) = U + 1 'buttons count
    md_msg(eMsgParams.pidButton + WinVersion) = VarPtr(lBtn(0)) 'ButtonID
    md_msg(eMsgParams.ppszButtonText + WinVersion) = VarPtr(sTxt(0)) 'Button text
    md_msg(eMsgParams.Timeout + WinVersion) = Timeout '
    MsgBoxEx = SoftModalMessageBox(md_msg(0))
End Function

**Comment by cristianbuse** [comment]
Hi,

I tried to run your code but I have VBA 64 bits and it does not work. I am sure with some conditional compilation can be made to run on 64 bits as well. However, this repo is intended to run on both Mac and Windows and so a native approach made the most sense. Thanks for your suggestion!
